### ISSUE TITLE
Clicking on a Users profile page as an unregistered user throws an Internal Server Error 

### ISSUE THREAD

**Issue by apoorv74** [justicehub-in/ckanext-justicehub_theme#105]
As the users page will only be visible to a registered user, we should direct such requests to the sign-up/login screen as we do when the user clicks on the contribute data link. 

![image](https://user-images.githubusercontent.com/5118689/109374154-32c5eb00-78d9-11eb-91c9-d779488e6d6d.png)

**Comment by Abhi2102** [comment]
User will now be prompted to login when clicking on a user name to see their profile
