### ISSUE TITLE
For some PDF reports views are not created.

### ISSUE THREAD

**Issue by karnsaurabhkumar** [justicehub-in/ckanext-justicehub_theme#106]
When one downloads the file the file name and the file extensions are incorrect. For example: https://justicehub.in/dataset/india-justice-report-2020/resource/86c3b1ee-384b-4e53-8009-ad770d39ad18

PDF can't be seen on the hub and downloading the PDF download a file with "download" name and no extension.

![image](https://user-images.githubusercontent.com/10262962/109375785-5858f180-78e5-11eb-892d-b64190834526.png)

**Comment by karnsaurabhkumar** [comment]
Found another example: 
https://justicehub.in/dataset/jobs-for-justice-s-corruption-in-the-supreme-court-of-india/resource/dfedcf3e-d0ee-4776-af98-1066647bd317

**Comment by karnsaurabhkumar** [comment]
CSV view is also not available for some of the file:

**Comment by karnsaurabhkumar** [comment]
For this dataset particularly, the datafile is a 3 GB file and a CSV. My guess is it is because of the file size that the system is unable to generate the view.

https://justicehub.in/dataset/contract-enforcement-litigation-nipfp/resource/5c6ca5d8-714b-4683-be96-977dfefd7346

**Comment by karnsaurabhkumar** [comment]
This dataset has PDF and view isn't generated

https://justicehub.in/dataset/supreme-courts-caseload-during-covid-19/resource/cced080b-c719-4b1e-99bb-449aef72bb82

**Comment by karnsaurabhkumar** [comment]
Found another instance where PDF view isn't gettting generated

https://justicehub.in/dataset/correctional-facilities-in-assam-2018

**Comment by Abhi2102** [comment]
Download link or view not getting created

- [ ] https://justicehub.in/dataset/india-justice-report-2020/resource/86c3b1ee-384b-4e53-8009-ad770d39ad18
- [ ] https://justicehub.in/dataset/jobs-for-justice-s-corruption-in-the-supreme-court-of-india/resource/dfedcf3e-d0ee-4776-af98-1066647bd317
- [ ] https://justicehub.in/dataset/supreme-courts-caseload-during-covid-19/resource/a3d7ef1a-4e9f-4749-9d99-288cb66a5c7f
- [ ] https://justicehub.in/dataset/contract-enforcement-litigation-nipfp/resource/5c6ca5d8-714b-4683-be96-977dfefd7346
- [ ] https://justicehub.in/dataset/supreme-courts-caseload-during-covid-19/resource/cced080b-c719-4b1e-99bb-449aef72bb82
- [ ] https://justicehub.in/dataset/correctional-facilities-in-assam-2018
- [ ] https://justicehub.in/dataset/special-leave-petitions-in-supreme-court-2001-2011
- [ ] https://justicehub.in/dataset/the-first-information-report-dataset-from-years-2015-2019

**Comment by Abhi2102** [comment]
fixed all the above issues with respective datasets and solved the issue of url not getting generated

**Comment by Abhi2102** [comment]
For https://justicehub.in/dataset/contract-enforcement-litigation-nipfp/resource/5c6ca5d8-714b-4683-be96-977dfefd7346 this No view is getting created because our datapusher is not able to identify the datatypes of columns correctly, maybe due to some data error or some other reason. We will fix this as part of #123 while switching to xloader instead of datapusher.
