### ISSUE TITLE
Account verification mail has placeholder saying - "Footer content will come here"

### ISSUE THREAD

**Issue by karnsaurabhkumar** [justicehub-in/ckanext-justicehub_theme#107]
Needs to be formatted and rewritten — requesting people to click on the link. And it says footer content will come here

![image](https://user-images.githubusercontent.com/10262962/109449264-fe376800-7a6d-11eb-8086-3e6e628f17d8.png)

**Comment by shashank-sharma** [comment]
@apoorv74 Let me know what content should be there in mail like:
```
Hello Shashank

Thank you for registering, here are the next steps:
...
...
```

Then I'll make necessary changes

**Comment by apoorv74** [comment]
@shashank-sharma let's use this template for now:

---
Hello [name],

Thank you for registering an account on the Justice Hub. 

Please click on this link[hyperlink] to validate your e-mail Id. Post this step, you will be able to contribute datasets on the [Justice Hub](https://justicehub.in/). 

For any queries, kindly reach out at [info@justicehub.in](mailto:info@justicehub.in). 

We look forward to collaborate with you. 

Regards,
The [JusticeHub](https://justicehub.in/about) team

**Comment by shashank-sharma** [comment]
Made changes, now it will look like:
![Screenshot from 2021-03-10 16-28-06](https://user-images.githubusercontent.com/9320644/110619733-28033400-81be-11eb-9e09-63017fae8836.png)

**Comment by shashank-sharma** [comment]
Updated in server, closing this issue
