### ISSUE TITLE
Explore popular categories does not render properly on mobile phone

### ISSUE THREAD

**Issue by karnsaurabhkumar** [justicehub-in/ckanext-justicehub_theme#108]
There are white spaces between different categories

![image](https://user-images.githubusercontent.com/10262962/109449345-350d7e00-7a6e-11eb-8777-3aa02dbfdbb3.png)

**Comment by akkisagiraju** [comment]
This is now fixed.

![image](https://user-images.githubusercontent.com/7601150/109786807-90d53400-7c33-11eb-9300-ce9545ea89d2.png)
