### ISSUE TITLE
Contact us form - Position of submit button on mobile view overlaps with the text

### ISSUE THREAD

**Issue by karnsaurabhkumar** [justicehub-in/ckanext-justicehub_theme#109]
![image](https://user-images.githubusercontent.com/10262962/109449414-60906880-7a6e-11eb-89f6-2ee5a96ca2fb.png)

**Comment by akkisagiraju** [comment]
The linked PR fixes this issue.

![image](https://user-images.githubusercontent.com/7601150/110077707-9f932680-7dac-11eb-8ce1-e436acb2179b.png)
