### ISSUE TITLE
Docs page - Message regarding release of Data portal needs to be rewritten/removed

### ISSUE THREAD

**Issue by karnsaurabhkumar** [justicehub-in/ckanext-justicehub_theme#110]
![image](https://user-images.githubusercontent.com/10262962/109449475-8f0e4380-7a6e-11eb-94f1-542bc5b5e47f.png)

**Comment by apoorv74** [comment]
@karnsaurabhkumar , we'll be revamping the docs website. Most of the content apart from the resources section will be removed. Please add all issues related to the docs website [here](https://github.com/justicehub-in/justice-hub-docs/issues)
