### ISSUE TITLE
"Writing effective query" - Can have better documentation

### ISSUE THREAD

**Issue by karnsaurabhkumar** [justicehub-in/ckanext-justicehub_theme#111]
Currently the effective query takes the user to CKAN documentation page. Ideally it would make sense for it to redirect to something in resources section. This is most likely an enhancement and not a bug.

https://docs.ckan.org/en/2.9/user-guide.html#search-in-detail

**Comment by apoorv74** [comment]
@karnsaurabhkumar we're tracking the issues for the documentation website [here](https://github.com/justicehub-in/justice-hub-docs/issues/28). 

We'll re-write specific components from this guide and convert it to an easier format.
