### ISSUE TITLE
No data contributors or group despite system being able to identify the right dataset

### ISSUE THREAD

**Issue by karnsaurabhkumar** [justicehub-in/ckanext-justicehub_theme#112]
I put DevDataLab in the search query. Website shows that no data contributors were found despite identifying the right dataset.

![image](https://user-images.githubusercontent.com/10262962/109471124-54200600-7a96-11eb-8ae1-e9b6b33edd40.png)

**Comment by karnsaurabhkumar** [comment]
Also it doesn't show any geography despite mentioning India in the description.

![image](https://user-images.githubusercontent.com/10262962/109471333-a4976380-7a96-11eb-8260-cf6dc15f946d.png)

**Comment by Abhi2102** [comment]
#121 to be fixed along this issue
