### ISSUE TITLE
Sorting the list after getting a result refreshes the entire page.

### ISSUE THREAD

**Issue by karnsaurabhkumar** [justicehub-in/ckanext-justicehub_theme#113]
These are the steps for replicating the issue:
1. Search for DevDataLab in the search query
2. Click on sort by and select by Name (A-Z)
3. The search result disappeared.

Ideal behaviour should keep the selection as is and sort among them.

**Comment by apoorv74** [comment]
Updating the issue:

- [ ] Fix the sort results as shared above
- [ ] Retain the search query on the search bar. It gives more context to the user if they can see whatever they have searched.

**Comment by Abhi2102** [comment]
Fixed.. Please check @apoorv74
