### ISSUE TITLE
Report error icon is missleading

### ISSUE THREAD

**Issue by karnsaurabhkumar** [justicehub-in/ckanext-justicehub_theme#114]
The icon is usually used to direct users for chatting but in our case we want user to report issues. Can we use a different icon?

![image](https://user-images.githubusercontent.com/10262962/109472927-bed24100-7a98-11eb-9beb-be2c8507b0b5.png)

**Comment by apoorv74** [comment]
@karnsaurabhkumar sure. Can you suggest an icon we can use here. This icon was taken from https://ikonate.com/
