### ISSUE TITLE
Resource view is not available for CSV files

### ISSUE THREAD

**Issue by karnsaurabhkumar** [justicehub-in/ckanext-justicehub_theme#122]
https://justicehub.in/dataset/justices-of-the-supreme-court-of-india-1950-2019/resource/3f3fe6d4-c148-4ac3-b45e-c1e11fae5fb0#

![image](https://user-images.githubusercontent.com/10262962/110891791-bee40380-8318-11eb-869a-9c43e8fdb4a5.png)

**Comment by Abhi2102** [comment]
One of the headings has a length greater than 63 characters, cause of which we are not able to write it into datastore. Have created an alternate view.
