### ISSUE TITLE
From date starts with 1985 right now. This needs to start from 1950 at least.

### ISSUE THREAD

**Issue by karnsaurabhkumar** [justicehub-in/ckanext-justicehub_theme#128]
There are datasets where the period of data covers ranges from 1950 to 2020. The from date right now on platform is 1985. Can we please move it to 1950 at least?

https://justicehub.in/dataset/background-of-indian-supreme-court-judges

![image](https://user-images.githubusercontent.com/10262962/114997803-de44f200-9ebd-11eb-8a12-9a82a8bd02f8.png)

**Comment by karnsaurabhkumar** [comment]
https://justicehub.in/dataset/justices-of-the-supreme-court-of-india-1950-2019

**Comment by Abhi2102** [comment]
Fixed - New  year range starts from 1900
