### ISSUE TITLE
Unable to scroll to get the log in button

### ISSUE THREAD

**Issue by karnsaurabhkumar** [justicehub-in/ckanext-justicehub_theme#130]
Hey,

Author of this dataset is unable to scroll to the log in button. https://justicehub.in/dataset/background-of-indian-supreme-court-judges

Steps for replication:
1. Visit Justicehub.in
2. Click on Join/Login

![image](https://user-images.githubusercontent.com/10262962/115380749-87f2ee80-a1f0-11eb-9591-5c42c52ced55.png)

**Comment by Abhi2102** [comment]
@karnsaurabhkumar  need more clarity on the issue.
