### ISSUE TITLE
You can view your file here after editing the dataset redirects to an undefined dataset

### ISSUE THREAD

**Issue by karnsaurabhkumar** [justicehub-in/ckanext-justicehub_theme#136]
I edited the below mentioned dataset and once saved, a message popped up saying you can view your dataset here. When I clicked on the link the dataset slug was undefined and the page error was 404. 

https://justicehub.in/dataset/habeas-corpus-petitions-in-the-supreme-court-from-2000-2019

**Comment by apoorv74** [comment]
@karnsaurabhkumar can you describe the steps here. Not able to replicate this at our end. Additionally, can you try editing it again ?

**Comment by Abhi2102** [comment]
@apoorv74 @karnsaurabhkumar  was able to replicate this with another dataset. will look into it.

**Comment by Abhi2102** [comment]
The issue was happening, when the dataset was getting updated only by changing file or desc of an exisiting resource and not adding any new resource. - Fixed
