### ISSUE TITLE
Add RSS feed link in the footer

### ISSUE THREAD

**Issue by apoorv74** [justicehub-in/ckanext-justicehub_theme#144]
We can include the links at a couple of places:

1. As an icon beside the twitter/github icons
2. Under the links section in the footer with text as `Subscribe`

RSS feed link - `https://justicehub.in/feeds/dataset.atom`

**Comment by akkisagiraju** [comment]
Commit #833b1b3 has the changes.

**Comment by akkisagiraju** [comment]
@apoorv74 The changes are live. This issue can be closed.
