### ISSUE TITLE
Create a dedicated summer of data page

### ISSUE THREAD

**Issue by apoorv74** [justicehub-in/ckanext-justicehub_theme#145]
### Sections to include

1. About the program
2. Mentors
3. Details of students along with photographs (Check doc for details)
4. Data release thumbnails
5. Blogs/Resources around the event
6. Partner session recordings (Check doc for details)
    1. Zombie tracker session
    2. Adv. Namit Saxena
    3. Adv. Shrutanjaya 

### Navigation

Proposed URL - `https://justicehub.in/events/summer-of-data-2021`

### Analytics

Update tracking details for this page on GA

### Docs

Working doc - [Link](https://docs.google.com/document/d/1Wav4-sBOsVUBMWnMA2Vf4EVqhtLuyNl7CxgMwzCRhCc/edit#)

**Comment by apoorv74** [comment]
@akkisagiraju this might also address #142

**Comment by apoorv74** [comment]
[Wireframe](https://github.com/justicehub-in/ckanext-justicehub_theme/issues/145)

What is the best way to display all the high courts in one - view?

We'll be releasing high courts datasets iteratively. For a user searching for data from a specific high court, they should be able to see it at once on this page, rather than searching for it. One way to implement this can be using a map like we see here - https://case.law/.

**Comment by apoorv74** [comment]
Blogs:

1. https://medium.com/@banerjeeswati08b/my-introduction-to-the-world-of-data-summer-of-data-by-justice-hub-90351909a489

**Comment by apoorv74** [comment]
Datasets:
- [Chhattisgarh](https://justicehub.in/dataset/dataset-on-judges-of-the-chhattisgarh-high-court)
- [Himachal pradesh](https://justicehub.in/dataset/groups/dataset-on-judges-of-the-himachal-pradesh-high-court)
- [Madras](https://justicehub.in/dataset/dataset-on-judges-of-the-madras-high-court)

**Comment by apoorv74** [comment]
Pending:

- [x] Mentor profiles
- [x] Content for the About section
- [x] Profile pic for `Shaswata Kapat`
- [x] Banner image
- [x] Add [Forum Link](https://forum.justicehub.in/t/queries-around-accessing-the-summer-of-data-datasets/120) under Resources
- [x] Update `Sessions` to `Guest Sessions`
- [ ] Update Sitemap
- [x] Add Analytics tag

**Comment by karnsaurabhkumar** [comment]
Two issue/suggestions:
(1) I think Shaswata Kapat's profile pic is missing. Let me know if its not in the folder I shared and I will ask him again.
(2) I think Ishita Khandelwal's profile picture is high size and loads very slowly. We may want to reduce the size to load faster.
(3) We have data on which Law schools they come from and it would be cool to have some way to show the representation of them. If we think its a graphics I think we can get it created to be put on the page.

**Comment by karnsaurabhkumar** [comment]
One more suggestion
(4) I see that youtube thumbnail that plays the video can not be maximised. Is there a way to enable this?

**Comment by akkisagiraju** [comment]
@karnsaurabhkumar 

1) Shaswata Kapat's picture is indeed in the folder but looks like it is either an invalid file or a corrupted one. We need a different image file.
2) I scaled down the image. It will load faster now.
3) This can be done. Do we just add school names below students' names? Or do you have a design in mind?
4) Made a change to allow fullscreen for all the three videos.

The changes for 2 and 4 will be live soon after the next pull to the dev server.

**Comment by apoorv74** [comment]
@akkisagiraju Bio for mentors is missing, can you check ?

**Comment by akkisagiraju** [comment]
@apoorv74 Updated the checklist.

**Comment by apoorv74** [comment]
@akkisagiraju Content for the About section:

---

Summer of Data is a 5-week program focused on bringing more law students into the open justice data movement. In this first edition of the Summer of Data Program, law students collaborated under the mentorship of Prof. Rangin Pallav Tripathy of NLU Odisha and CivicDataLab to create a dataset that profiles the backgrounds of High Court Judges from across India.

Data (or the lack thereof) on judges, their backgrounds, tenure and professional trajectory can tell us a lot about the judicial system. It can reveal the diversity and transparency of the institution on a range of parameters. Equally it can unravel systemic factors that affect the composition and impact of the institution.

The entire program was conducted online between May 31st-July 2nd, 2021. The data curation exercise was followed by rounds of data validations that involved manual and automated checks to ensure that the quality of datasets is not compromised. All datasets and related documentation will be released on the Justice Hub under the CC BY 4.0 License.

A shout-out to the team at [Internet Freedom Foundation](internetfreedom.in/), Adv. Namit Saxena and Adv. Shrutanjaya Bhardwaj for inspiring the students, by sharing their stories and several key insights around data driven work in the areas of law and justice, during the guest sessions.

**Comment by karnsaurabhkumar** [comment]
@akkisagiraju - Sharing my bio for the page:

Saurabh currently works with Agami where he leads Data for Justice. He is passionate about creative use of data and digital technologies to solve complex societal problems. Outside of work, you will find him reading graphic novels, listening to music and grooving on Indian rap songs. Currently he is trying to find ways to build a movement of young change makers who harness the power of data for justice innovation.

**Comment by apoorv74** [comment]
Page Updates:

- [x] Update the links to the video:

1. Shrutanjaya - https://youtu.be/fOtJ7vATd_4
2. IFF team - https://youtu.be/m7GWV_i0XPM
3. Ad. Namit Saxena - https://youtu.be/suLk2gvLrCI

- [x] Update the dataset links 

All datasets are categorised within the `Summer of Data` group tag - https://justicehub.in/dataset?groups=summer-of-data

**Comment by akkisagiraju** [comment]
@apoorv74 The above two changes are done and are live on dev server.

https://dev.justicehub.in/events/summer-of-data-2021

**Comment by apoorv74** [comment]
Add link under **Blogs and Resources**

[Who is a Judge? Solving the Problem of Insufficiency of Judicial Data
](https://www.barandbench.com/apprentice-lawyer/who-is-a-judge-insufficiency-of-judicial-data)

**Comment by apoorv74** [comment]
> Add link under **Blogs and Resources**
> 
> [Who is a Judge? Solving the Problem of Insufficiency of Judicial Data ](https://www.barandbench.com/apprentice-lawyer/who-is-a-judge-insufficiency-of-judicial-data)

Added - https://github.com/justicehub-in/ckanext-justicehub_theme/commit/92dcbaa0f525035681e21363979723487a03c019

**Comment by apoorv74** [comment]
The page is live here - https://justicehub.in/events/summer-of-data-2021
