### ISSUE TITLE
Update the banner image for Summer of Data on the homepage

### ISSUE THREAD

**Issue by apoorv74** [justicehub-in/ckanext-justicehub_theme#146]
@karnsaurabhkumar will share the updated image.

**Comment by apoorv74** [comment]
Images shared by @karnsaurabhkumar 

![Summer of Data Banner (3)](https://user-images.githubusercontent.com/5118689/128808669-d6df3862-649d-485b-beef-7dd91fd875a8.png)

**Comment by apoorv74** [comment]
@akkisagiraju can we use this on the homepage and on the SoD page ?

**Comment by akkisagiraju** [comment]
@apoorv74 Made the changes to include this image on homepage and the latest SoD events page.

**Comment by apoorv74** [comment]
@akkisagiraju this is the updated banner image

![Summer of Data Banner (3)](https://user-images.githubusercontent.com/5118689/128893305-7a245ed8-1adf-4e8b-8d1a-6f5d314466ad.png)

**Comment by akkisagiraju** [comment]
@apoorv74 Replaced the banner image with the one above.

**Comment by karnsaurabhkumar** [comment]
Links to the video:

Shrutanjaya - https://youtu.be/fOtJ7vATd_4
IFF team - https://youtu.be/m7GWV_i0XPM
Ad. Namit Saxena - https://youtu.be/suLk2gvLrCI
