### ISSUE TITLE
Remove default month from the uploaded reports

### ISSUE THREAD

**Issue by apoorv74** [justicehub-in/ckanext-justicehub_theme#43]
For the question - _Which time period does this data cover?_ The month field is optional, but January is getting saved as the default month for these reports:

1 - India Justice Report - 2019
2 - India Justice Report - 2020
3 - The First Information Report Data set from 2015 - 2019

We should also remove the deafult month from these uploads and only consider the Year field

**Comment by akkisagiraju** [comment]
Assigned to @Abhi2102 as this needs change in the DB. I fixed the month defaulting to January issue [here](https://github.com/justicehub-in/ckanext-justicehub_theme/issues/38).

**Comment by akkisagiraju** [comment]
Closing this as the edit feature is now live and a user can edit an already uploaded dataset.
