### ISSUE TITLE
UI issues on Explore Datasets page

### ISSUE THREAD

**Issue by akkisagiraju** [justicehub-in/ckanext-justicehub_theme#46]
- [x] Misalignment of sidebar and search results on some resolutions.
- [x] Limit the description size of a resource in search results (reduce the number of characters). 
- [x] Hyperlink the "View all files in this dataset" button.
- [x] Fix the file type icon's size.
- [x] In the dataset view, limit the number of files to 4 or 5 per dataset

**Comment by akkisagiraju** [comment]
- [ ] Misalignment of sidebar and search results on some resolutions.
- [x] Limit the description size of a resource in search results (reduce the number of characters). 
- [x] Hyperlink the "View all files in this dataset" button.
- [x] Fix the file type icon's size.
- [x] In the dataset view, limit the number of files to 4 or 5 per dataset

First one needs testing on multiple devices/resolutions and browsers before closing.

**Comment by apoorv74** [comment]
- [ ] Highlight active/selected category on the page. Currently one cannot see visually what category is selected.
