### ISSUE TITLE
Licences to include for data and content 

### ISSUE THREAD

**Issue by apoorv74** [justicehub-in/ckanext-justicehub_theme#50]
- Include all CC licenses from this [list](https://creativecommons.org/about/cclicenses/)
- Include open data licences from this [list](https://opendatacommons.org/licenses/)

**Comment by apoorv74** [comment]
`[
  {
    "domain_content": "",
    "domain_data": "",
    "domain_software": "",
    "family": "",
    "id": "",
    "is_generic": "",
    "maintainer": "",
    "od_conformance": "",
    "osd_conformance": "",
    "status": "",
    "title": "Creative Commons Attribution 4.0 International (CC BY 4.0)",
    "url": "https://creativecommons.org/licenses/by/4.0/"
  },
  {
    "domain_content": "",
    "domain_data": "",
    "domain_software": "",
    "family": "",
    "id": "",
    "is_generic": "",
    "maintainer": "",
    "od_conformance": "",
    "osd_conformance": "",
    "status": "",
    "title": "Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)",
    "url": "https://creativecommons.org/licenses/by-sa/4.0/"
  },
  {
    "domain_content": "",
    "domain_data": "",
    "domain_software": "",
    "family": "",
    "id": "",
    "is_generic": "",
    "maintainer": "",
    "od_conformance": "",
    "osd_conformance": "",
    "status": "",
    "title": "Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)",
    "url": "https://creativecommons.org/licenses/by-nc/4.0/"
  },
  {
    "domain_content": "",
    "domain_data": "",
    "domain_software": "",
    "family": "",
    "id": "",
    "is_generic": "",
    "maintainer": "",
    "od_conformance": "",
    "osd_conformance": "",
    "status": "",
    "title": "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)",
    "url": "https://creativecommons.org/licenses/by-nc-sa/4.0/"
  },
  {
    "domain_content": "",
    "domain_data": "",
    "domain_software": "",
    "family": "",
    "id": "",
    "is_generic": "",
    "maintainer": "",
    "od_conformance": "",
    "osd_conformance": "",
    "status": "",
    "title": "Creative Commons Attribution-NoDerivatives 4.0 International (CC BY-ND 4.0)",
    "url": "https://creativecommons.org/licenses/by-nd/4.0/"
  },
  {
    "domain_content": "",
    "domain_data": "",
    "domain_software": "",
    "family": "",
    "id": "",
    "is_generic": "",
    "maintainer": "",
    "od_conformance": "",
    "osd_conformance": "",
    "status": "",
    "title": "Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)",
    "url": "https://creativecommons.org/licenses/by-nc-nd/4.0/"
  },
  {
    "domain_content": "",
    "domain_data": "",
    "domain_software": "",
    "family": "",
    "id": "",
    "is_generic": "",
    "maintainer": "",
    "od_conformance": "",
    "osd_conformance": "",
    "status": "",
    "title": "CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
    "url": "https://creativecommons.org/publicdomain/zero/1.0/"
  },
  {
    "domain_content": "",
    "domain_data": "",
    "domain_software": "",
    "family": "",
    "id": "",
    "is_generic": "",
    "maintainer": "",
    "od_conformance": "",
    "osd_conformance": "",
    "status": "",
    "title": "Open Data Commons Open Database License (ODbL)",
    "url": "https://opendatacommons.org/licenses/odbl/"
  },
  {
    "domain_content": "",
    "domain_data": "",
    "domain_software": "",
    "family": "",
    "id": "",
    "is_generic": "",
    "maintainer": "",
    "od_conformance": "",
    "osd_conformance": "",
    "status": "",
    "title": "Open Data Commons Attribution License (ODC-By)",
    "url": "https://opendatacommons.org/licenses/by/"
  },
  {
    "domain_content": "",
    "domain_data": "",
    "domain_software": "",
    "family": "",
    "id": "",
    "is_generic": "",
    "maintainer": "",
    "od_conformance": "",
    "osd_conformance": "",
    "status": "",
    "title": "Open Data Commons Public Domain Dedication and License (PDDL)",
    "url": "https://opendatacommons.org/licenses/pddl/"
  }
]`

**Comment by akkisagiraju** [comment]
Updated the list of licenses on the upload flow and on the dataset page.

**Comment by akkisagiraju** [comment]
Closing the issue.
