### ISSUE TITLE
UI Issues on the Dataset Page

### ISSUE THREAD

**Issue by apoorv74** [justicehub-in/ckanext-justicehub_theme#56]
- [x] Inclde the link to go back to the dataset page from the file page. Check `View All Files` link on the prototype
- [x] File preview (PDF or CSV) should be above the summary text
- [x] Add date of release (which is the date of publication) on the page below the dataset title
- [x] Change `Uploaded on` to `Uploaded`
- [x] In case of multiple geographies there is an extra trailing comma at the end. Check [here](https://justicehub.in/dataset/satarc-a-household-survey-in-four-major-indian-cities)
- [x] In case of multiple reference links, add one per line

**Comment by akkisagiraju** [comment]
Update: Four of the issues are now fixed.

- [ ] Inclde the link to go back to the dataset page from the file page. Check `View All Files` link on the prototype
- [ ] File preview (PDF or CSV) should be above the summary text
- [x] Add date of release (which is the date of publication) on the page below the dataset title
- [x] Change `Uploaded on` to `Uploaded`
- [x] In case of multiple geographies there is an extra trailing comma at the end. Check [here](https://justicehub.in/dataset/satarc-a-household-survey-in-four-major-indian-cities)
- [ ] Link the licences and use full text of the license
- [ ] Data Source[s] should be hyperlinked as well. One data source per line
- [x] In case of multiple reference links, add one per line
- [ ] Link org name to the orgs website in case owner is an organisation

**Comment by akkisagiraju** [comment]
Latest linked PR fixes the first two issues.

**Comment by apoorv74** [comment]
- [ ] Remove trailing slashes from the Date of Publication in case date and month are not available. Currently it reads as `Date of Publication: //2017`
