### ISSUE TITLE
UI Issues - HomePage

### ISSUE THREAD

**Issue by apoorv74** [justicehub-in/ckanext-justicehub_theme#59]
- [ ] Replace the text - `Want to see your name here? We’re looking for contributors!` with `Can’t find what you are looking for?`
- [ ] Replace the text for the `Contribute Data` button (right above the footer) to `Let us know!`
- [ ] Text to be used for the highlights section (substack CTA) is [here](https://docs.google.com/document/d/16BVCBQlENmuvFfJBasxzDIJ_r91iPZGM8or1M_aDeTM/edit#bookmark=id.wwuc9mnvsn8k)
- [ ] Add testimonials - Content [here](https://docs.google.com/document/d/16BVCBQlENmuvFfJBasxzDIJ_r91iPZGM8or1M_aDeTM/edit#bookmark=id.pc9b4pp6lige)
- [ ] Change Categories title to Title Case - `Explore Popular Categories`

From the footer:
- [ ] Remove the link for _Blog_
- [ ] Redirect _Resources_ to docs.justicehub.in
- [ ] Redirect Explore dataset to https://justicehub.in/dataset
- [ ] Redirect Contribute data to https://justicehub.in/upload
- [ ] Remove subscribe text box 
- [ ] Remove the text `Subscribe to our mailing list`
- [ ] Remove the text `Enter your email:`
- [ ] Replace the text on the Subscribe button to `Subscribe to our newsletter`
- [ ] Redirect the subscibre link to dataforjustice.substack.com/

**Comment by akkisagiraju** [comment]
These are now added via the linked PR. Closing the issue.
