### ISSUE TITLE
Update content for the About Us Page

### ISSUE THREAD

**Issue by apoorv74** [justicehub-in/ckanext-justicehub_theme#62]
Check [this doc](https://docs.google.com/document/d/1vHyIg4349vzzLZHOro1L5qfSkUNY9aL6vKJbbA7qAsI/edit?ts=602a4b50) for content

For updated UI check this [doc](https://drive.google.com/file/d/1okHjafvRhaene4LQUEqKaUKY6pl8sP6p/view?usp=sharing)

**Comment by akkisagiraju** [comment]
Updated the content on the About Us page.

**Comment by apoorv74** [comment]
**Team images**

All apart form Saurabh and Varun are [here](https://docs.justicehub.in/people/) - We dont need to categorise them by the team. Just on the basis of alphabetical order as per the prototype

[CDL Logo](https://drive.google.com/drive/folders/16uwxbQCGHtdrHewOfjL8oz7BZrcStiqi) 
Agami Logo - We have one in the footer, else please check it [here](agami.in/).

**Comment by apoorv74** [comment]
Changes suggested for the About Us page:

1 - Only include active team members. 
2 - In the advisors section, for Samar mention  - Founder- Article 14

**Comment by apoorv74** [comment]
[Agami logo to use](https://drive.google.com/drive/folders/1C4Uu0dwisiQ3BPvWN8n9dGf35zYOz5OZ?usp=sharing)
