### ISSUE TITLE
Hamburger navigation isn't working on some pages

### ISSUE THREAD

**Issue by akkisagiraju** [justicehub-in/ckanext-justicehub_theme#73]

**Comment by siddharthdeo99** [comment]
Hey, can you exactly tell me on which page it isn't working?

**Comment by akkisagiraju** [comment]
@siddharthdeo99 Hi Siddarth, thank you for your interest in contributing to Justice Hub! At the moment, we are not ready to accept public contributions. Feel free to come back in a few weeks.
