### ISSUE TITLE
Assign categories to datasets / Add datasets to groups

### ISSUE THREAD

**Issue by apoorv74** [justicehub-in/ckanext-justicehub_theme#80]
New Groups Added:

- Judicial Reforms - [SVG](https://drive.google.com/uc?id=1wKQArkUKDlofGVcYDa5oI4xuMZZ-ZTxT)
- Judges - [SVG](https://drive.google.com/uc?id=1aL9BhsSFcnSpwA16K3tRp3jiDokx-6Oo)
- Laws - [SVG](https://drive.google.com/uc?id=1G-Tkd1qEmoVijraqaySjsK7dHHiq8_E3)
- Prison - [SVG](https://drive.google.com/uc?id=1fUiQy_wRMbVrOXkcSi5E0Wnnkej-Sv0W)

**Comment by Abhi2102** [comment]
These logos have the creators name written below them.. can we use something without a name.

**Comment by apoorv74** [comment]
@Abhi2102 @akkisagiraju updated the SVG links.
