### ISSUE TITLE
Add contributor details on the home page

### ISSUE THREAD

**Issue by apoorv74** [justicehub-in/ckanext-justicehub_theme#81]
**Organisations**

- Indian Kanoon - [Image]()
- HAQ - CRC - [Image](https://drive.google.com/file/d/16IOJwL94ymNqaBOFkoCHnHEu-9J6Sq1S/view?usp=sharing)
- Project 39A - [Image](https://drive.google.com/file/d/1_p_0KP83dm0fopNUvOYbn0sZy__anHpb/view?usp=sharing)
- Vidhi - [Image](https://staging.justicehub.in/uploads/group/2020-08-03-103353.648745vidhi-logo.jpg)
- IGIDR - [Image](https://staging.justicehub.in/uploads/group/2020-07-02-133023.256980igidr-logo.png)
- NIPFP - [Image](https://staging.justicehub.in/uploads/group/2020-07-02-041938.839776nipfp-logo.png)
- CLPR - [Image](https://clpr.org.in/wp-content/themes/redstart-clpr/assets/images/clpr-logo.svg)
- IDFC - [Image](https://www.idfcinstitute.org/site/assets/files/1044/logo.svg)
- Tata Trusts - [Image](https://staging.justicehub.in/uploads/group/2020-06-23-075908.759080TATA-Trusts-Red-Logoscaled.png) 
- DevDataLab - [Image](https://shrug-assets-ddl.s3.amazonaws.com/static/main/assets/img/ddl_logo.png)
- Studio Nilima - [Image](https://drive.google.com/file/d/1IJAlt6UBwovwb7EumK5dWlFeOsmVPX8V/view?usp=sharing)
- Internet Freedom Foundation - [Image](https://drive.google.com/file/d/1DUYl3MGwG6OzyMXlKt45jFvWka6RJ1eE/view?usp=sharing)

**Individuals**

- Madhav S Aney - [Image](http://www.mysmu.edu/faculty/madhavsa/Photo.jpg)
- Manaswini Rao - [Image](http://manaswinirao.com/images/RAOPhoto_2014-8.jpg)
- Johannes Boehm - [Image](https://jmboehm.github.io/jboehm-13-cropped.jpg)
- Amrit Amirapu - [Image](https://sites.google.com/site/amritamirapu/_/rsrc/1439237140775/home/photo_rotate.JPG)

**Comment by akkisagiraju** [comment]
Indian Kanoon is missing its logo.

The rest are added on the homepage.

**Comment by apoorv74** [comment]
> 
> 
> Indian Kanoon is missing its logo.
> 
> The rest are added on the homepage.

[Indian Kanoon logo](https://indiankanoon.org/static/pics/indiankanoon_top.png)

**Comment by apoorv74** [comment]
Update CHRI's logo
![CHRI Logo_Aug 2017](https://user-images.githubusercontent.com/5118689/113268456-04cb3080-92f5-11eb-8e98-ef98f49384fc.png)

**Comment by akkisagiraju** [comment]
Updated the logo.

**Comment by akkisagiraju** [comment]
Closing the issue as the changes are available on justicehub.in now.
