### ISSUE TITLE
Additional metadata fields required for datasets

### ISSUE THREAD

**Issue by apoorv74** [justicehub-in/ckanext-justicehub_theme#82]
- [x] Dataset description
- [x] Organisation website, in case contributor is an organisation
- [x] Individual website, in case contributor is an individual
- [x] Last edit date for datasets

**Comment by Abhi2102** [comment]
License and source issue has been removed from here since there are separate issue ids for them

**Comment by akkisagiraju** [comment]
The linked PR fixes all these issues.
